CREATE TABLE IF NOT EXISTS transactions (
    -- PRIMARY KEY: ULID (Universally Unique Lexicographically Sortable Identifier)
    -- Format: 26 characters, base32 encoded, sortable by creation time
    -- Example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
    -- Benefits: URL-friendly, shorter than UUID, sortable, collision-resistant
    id CHAR(26) PRIMARY KEY,

    -- Idempotency key: unique identifier for preventing duplicate requests
    -- Generated by combining merchant_id + order_reference + timestamp
    -- Ensures same request retried multiple times creates only one transaction
    idempotency_key VARCHAR(64) UNIQUE NOT NULL,

    -- Transaction type defines the operation being performed
    -- AUTH: Initial authorization (reserves funds)
    -- CAPTURE: Captures previously authorized funds
    -- REFUND: Returns money to the customer
    type ENUM('AUTH', 'CAPTURE', 'REFUND') NOT NULL,

    -- Current state of the transaction (expanded for better tracking)
    -- PENDING: Created, awaiting processing
    -- PROCESSING: Currently being processed by payment gateway
    -- APPROVED: Successfully completed
    -- DECLINED: Rejected by validation or payment gateway
    -- EXPIRED: Authorization expired before capture
    -- CANCELLED: Manually cancelled by merchant or customer
    -- FAILED: Technical error during processing
    status ENUM('PENDING', 'PROCESSING', 'APPROVED', 'DECLINED', 'EXPIRED', 'CANCELLED', 'FAILED')
           NOT NULL DEFAULT 'PENDING',

    -- Transaction amount with validation
    -- DECIMAL(12,2): up to 9,999,999,999.99 (12 total digits, 2 decimals)
    amount DECIMAL(12,2) NOT NULL CHECK (amount > 0),

    -- Currency using ENUM for validation and performance
    -- Restricted to supported currencies only
    currency ENUM('CLP', 'USD', 'EUR', 'GBP') NOT NULL,

    -- Merchant identifier (reduced from 64 to 32 chars, sufficient for most IDs)
    merchant_id VARCHAR(32) NOT NULL,

    -- Merchant's unique order/purchase reference
    order_reference VARCHAR(128) NOT NULL,

    -- Parent transaction ID for creating transaction chains
    -- NULL for AUTH transactions (they have no parent)
    -- CAPTURE points to its AUTH transaction
    -- REFUND points to its CAPTURE or AUTH transaction
    parent_id CHAR(26) NULL,

    -- Country code with validation (ISO 3166-1 alpha-2)
    -- Must be exactly 2 uppercase letters
    country_code CHAR(2) NOT NULL CHECK (country_code REGEXP '^[A-Z]{2}$'),

    -- Flexible metadata in JSON format
    -- Stores additional custom data without schema modifications
    -- Can include: {"customer_email": "...", "city": "Santiago", "device": "mobile"}
    metadata JSON NULL,

    -- Error code for failed/declined transactions
    -- Standardized codes: INSUFFICIENT_FUNDS, CARD_EXPIRED, NETWORK_ERROR
    error_code VARCHAR(64) NULL,

    -- Audit: creation timestamp with millisecond precision (immutable)
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    -- Audit: timestamp of last status change
    -- Updated whenever status field changes
    status_updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    -- Processing completion timestamp
    -- Set when transaction moves from PENDING to final state (APPROVED/DECLINED/FAILED)
    -- Allows calculating processing latency: processed_at - created_at
    processed_at TIMESTAMP(3) NULL,

    -- Performance indexes for common query patterns
    INDEX idx_merchant (merchant_id),
    INDEX idx_country (country_code),
    INDEX idx_status (status),
    INDEX idx_type (type),
    INDEX idx_created_at (created_at),
    INDEX idx_merchant_status (merchant_id, status),
    INDEX idx_idempotency (idempotency_key),

    -- Foreign key ensures referential integrity
    FOREIGN KEY (parent_id)
        REFERENCES transactions(id)
        ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
